[profile.default]
#src = "src"
src = "src/defi_erc20/ourtoken.sol"
#ourtoken
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/chainlin-brownie",

"@openzeppelin=lib/openzeppelin-contracts"]
#"@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"
#"@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/security"


[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[invariant]
runs = 64
depth = 64
fail_on_revert = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
